### ISSUE TITLE
New parser fails with lower case instructions

### ISSUE THREAD

**Issue by nrkn** [nrkn/hrm-parser#5]

**Comment by sixlettervariables** [comment]
I'm actually making mine case sensitive (maybe...). The game does not accept lower-case instructions, nor does it accept labels which exactly match instructions (so `INBOX:` is invalid, but `inbox:` is valid).

**Comment by nrkn** [comment]
How about that, I'd never tried it in the game. Thanks for that!

**Comment by sixlettervariables** [comment]
I'm opening issues on `hrm-grammar` for these sort of "findings" w.r.t. my grammar. I'm building up sets of "good" and "bad" examples.
